// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: readingprogress.proto

package readingprogress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId      int32  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId      int32  `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
	PagesNumber int32  `protobuf:"varint,4,opt,name=pagesNumber,proto3" json:"pagesNumber,omitempty"`
	CreatedAt   string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *ReadingProgress) Reset() {
	*x = ReadingProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readingprogress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadingProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingProgress) ProtoMessage() {}

func (x *ReadingProgress) ProtoReflect() protoreflect.Message {
	mi := &file_readingprogress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingProgress.ProtoReflect.Descriptor instead.
func (*ReadingProgress) Descriptor() ([]byte, []int) {
	return file_readingprogress_proto_rawDescGZIP(), []int{0}
}

func (x *ReadingProgress) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadingProgress) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadingProgress) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ReadingProgress) GetPagesNumber() int32 {
	if x != nil {
		return x.PagesNumber
	}
	return 0
}

func (x *ReadingProgress) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReadingProgresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadingProgresses []*ReadingProgress `protobuf:"bytes,1,rep,name=readingProgresses,proto3" json:"readingProgresses,omitempty"`
}

func (x *ReadingProgresses) Reset() {
	*x = ReadingProgresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readingprogress_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadingProgresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingProgresses) ProtoMessage() {}

func (x *ReadingProgresses) ProtoReflect() protoreflect.Message {
	mi := &file_readingprogress_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingProgresses.ProtoReflect.Descriptor instead.
func (*ReadingProgresses) Descriptor() ([]byte, []int) {
	return file_readingprogress_proto_rawDescGZIP(), []int{1}
}

func (x *ReadingProgresses) GetReadingProgresses() []*ReadingProgress {
	if x != nil {
		return x.ReadingProgresses
	}
	return nil
}

type GetReadingProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId int32 `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *GetReadingProgressRequest) Reset() {
	*x = GetReadingProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readingprogress_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadingProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingProgressRequest) ProtoMessage() {}

func (x *GetReadingProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readingprogress_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingProgressRequest.ProtoReflect.Descriptor instead.
func (*GetReadingProgressRequest) Descriptor() ([]byte, []int) {
	return file_readingprogress_proto_rawDescGZIP(), []int{2}
}

func (x *GetReadingProgressRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type CreateReadingProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId      int32 `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	PagesNumber int32 `protobuf:"varint,3,opt,name=pagesNumber,proto3" json:"pagesNumber,omitempty"`
}

func (x *CreateReadingProgressRequest) Reset() {
	*x = CreateReadingProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readingprogress_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReadingProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadingProgressRequest) ProtoMessage() {}

func (x *CreateReadingProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readingprogress_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadingProgressRequest.ProtoReflect.Descriptor instead.
func (*CreateReadingProgressRequest) Descriptor() ([]byte, []int) {
	return file_readingprogress_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReadingProgressRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReadingProgressRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateReadingProgressRequest) GetPagesNumber() int32 {
	if x != nil {
		return x.PagesNumber
	}
	return 0
}

var File_readingprogress_proto protoreflect.FileDescriptor

var file_readingprogress_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53, 0x0a, 0x11, 0x52,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x3e, 0x0a, 0x11, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x11, 0x72,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x22, 0x33, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x73, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xa0, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x72,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_readingprogress_proto_rawDescOnce sync.Once
	file_readingprogress_proto_rawDescData = file_readingprogress_proto_rawDesc
)

func file_readingprogress_proto_rawDescGZIP() []byte {
	file_readingprogress_proto_rawDescOnce.Do(func() {
		file_readingprogress_proto_rawDescData = protoimpl.X.CompressGZIP(file_readingprogress_proto_rawDescData)
	})
	return file_readingprogress_proto_rawDescData
}

var file_readingprogress_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_readingprogress_proto_goTypes = []any{
	(*ReadingProgress)(nil),              // 0: ReadingProgress
	(*ReadingProgresses)(nil),            // 1: ReadingProgresses
	(*GetReadingProgressRequest)(nil),    // 2: GetReadingProgressRequest
	(*CreateReadingProgressRequest)(nil), // 3: CreateReadingProgressRequest
}
var file_readingprogress_proto_depIdxs = []int32{
	0, // 0: ReadingProgresses.readingProgresses:type_name -> ReadingProgress
	3, // 1: ReadingService.CreateReadingProgress:input_type -> CreateReadingProgressRequest
	2, // 2: ReadingService.GetReadingProgress:input_type -> GetReadingProgressRequest
	0, // 3: ReadingService.CreateReadingProgress:output_type -> ReadingProgress
	1, // 4: ReadingService.GetReadingProgress:output_type -> ReadingProgresses
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_readingprogress_proto_init() }
func file_readingprogress_proto_init() {
	if File_readingprogress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_readingprogress_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReadingProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_readingprogress_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReadingProgresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_readingprogress_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetReadingProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_readingprogress_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReadingProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_readingprogress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readingprogress_proto_goTypes,
		DependencyIndexes: file_readingprogress_proto_depIdxs,
		MessageInfos:      file_readingprogress_proto_msgTypes,
	}.Build()
	File_readingprogress_proto = out.File
	file_readingprogress_proto_rawDesc = nil
	file_readingprogress_proto_goTypes = nil
	file_readingprogress_proto_depIdxs = nil
}
